### ISSUE TITLE
Problems with HTML content

### ISSUE THREAD

**Issue by artps** [zhuowei/Xenologer#25]
The text comes fine

![screen shot 2013-06-21 at 11 28 04](https://f.cloud.github.com/assets/109670/685828/233417b6-da44-11e2-8438-6eb8be44a727.png)

But HTML…
![screen shot 2013-06-21 at 11 16 06](https://f.cloud.github.com/assets/109670/685818/b3df0f88-da43-11e2-8196-2e50de23a6a2.png)

Anyone knows where the problem is?

// Android 4.2

**Comment by zhuowei** [comment]
Do you have a LogCat of the output?

**Comment by artps** [comment]
Yeah, I have logs: https://gist.github.com/arsemyonov/c3fb192f9db7ee1e9f53

**Comment by artps** [comment]
I tried to decrease resolution to 420x320, 120dpi, but got the same result.
![screen shot 2013-06-21 at 23 40 33](https://f.cloud.github.com/assets/109670/689153/7af17e7e-daaa-11e2-80db-eb07659fda65.png)

Some icons with `<img>` was loaded, but text — no. It's strange

**Comment by zhuowei** [comment]
I'll try to reproduce it on my Nexus 7. Thanks for your help.

**Comment by zhuowei** [comment]
Confirmed: Nexus 7 running Xenologer APKs, CNN Glassware

**Comment by zhuowei** [comment]
Basically, the renderer was looking for fonts where Glass stores them, in /system/glass_fonts/, and was confused when it couldn't find it.
I modified the paths in the stylesheet, but then it turns out Google automatically wipes the stylesheet and replaces it with a brand new copy from the Cloud, so I disabled that updater.
As a consequence, though, you need to reinstall, then clear the data associated with GlassHome.

**Comment by artps** [comment]
Amazing, it's working. Thanks a lot!
